language: vi

pipeline:
- name: "WhitespaceTokenizer"  # Tokenizer để tách từ
- name: "LanguageModelFeaturizer"  # Dùng PhoBERT để hiểu tiếng Việt tốt hơn
  model_name: "bert"
  model_weights: "vinai/phobert-base"
  cache_dir: "/content/drive/MyDrive/CacheRASA"
- name: "RegexFeaturizer"  # Nhận diện mẫu regex trong câu
- name: "LexicalSyntacticFeaturizer"  # Trích xuất đặc trưng ngữ pháp
- name: "CountVectorsFeaturizer"  # Vector hóa từ
- name: "CountVectorsFeaturizer"  # Vector hóa ký tự (ngram)
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: "RegexEntityExtractor"  # Trích xuất entity dựa trên regex
  case_sensitive: False  # Không phân biệt hoa thường
  use_lookup_tables: True  # Sử dụng bảng tra cứu từ
- name: "DIETClassifier"  # Nhận diện intent & entity
  epochs: 100
  learning_rate: 0.0005
  tensorboard_log_directory: "./tb_logs"
  checkpoint_model: true
  evaluate_every_number_of_epochs: 5
  drop_rate: 0.4
  weight_sparsity: 0.5
- name: "EntitySynonymMapper"  # Xử lý từ đồng nghĩa
- name: "ResponseSelector"  # Chọn phản hồi phù hợp
  epochs: 50
- name: "FallbackClassifier"  # Xử lý khi chatbot không chắc chắn
  threshold: 0.3
  ambiguity_threshold: 0.1

policies:
- name: "MemoizationPolicy"
- name: "RulePolicy"
- name: "TEDPolicy"
  max_history: 5
  epochs: 50
  checkpoint_model: true
  evaluate_every_number_of_epochs: 10
  tensorboard_log_directory: "./tb_logs"
